### ISSUE TITLE
[Bug] Error when toggle channel ignorable.

### ISSUE THREAD

**Issue by SrBedrock** [Hexaoxide/Carbon#29]
<details>
<summary>Console error</summary>

```
[01:33:51 ERROR]: [CarbonChat] [ACF] Exception in command: tch global
[01:33:51 ERROR]: [CarbonChat] [ACF] java.lang.reflect.InvocationTargetException
[01:33:51 ERROR]: [CarbonChat] [ACF]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at java.lang.reflect.Method.invoke(Unknown Source)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.libs.co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:154)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.libs.co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.libs.co.aikar.commands.BaseCommand.execute(BaseCommand.java:513)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.libs.co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.libs.co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1923)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1734)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1192)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1185)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1161)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at java.lang.Thread.run(Unknown Source)
[01:33:51 ERROR]: [CarbonChat] [ACF] Caused by: java.lang.NullPointerException
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.storage.impl.SimpleUserChannelSettings.setIgnoring(SimpleUserChannelSettings.java:60)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.storage.UserChannelSettings.setIgnoring(UserChannelSettings.java:17)
[01:33:51 ERROR]: [CarbonChat] [ACF]    at net.draycia.carbon.commands.ToggleCommand.baseCommand(ToggleCommand.java:33)
[01:33:51 ERROR]: [CarbonChat] [ACF]    ... 27 more
```

</details>

<details>
<summary>config.yml</summary>

```yml
# CarbonChat Docs:
# https://github.com/Draycia/Chat/wiki

# Set this to false to disable warnings and tips when the plugin thinks there may be configuration issues.
show-tips: true

# All of the settings under this 'default' section can be applied to each channel individually to override these.
# These are provided as a way to configure default channel settings.
default:
  # switch-message, toggle-off-message and toggle-on-message support PlaceholderAPI
  switch-message: '<gray>Você entrou no canal <color><channel><gray>!'
  switch-other-message: '<gray><player> entrou no canal <color><channel><gray>!'
  switch-failure-message: '<red>Você não pode usar o canal <channel>!'
  toggle-on-message: '<gray>Você receberá mensagens do canal <color><channel><gray>!'
  toggle-off-message: '<gray>Você não receberá mensagens do canal <color><channel><gray>!'
  toggle-other-on: '<gray><player> receberá mensagens do canal <color><channel><gray>!'
  toggle-other-off: '<gray><player> não receberá mensagens do canal <color><channel><gray>!'
  cannot-use-channel: "<red>Você não pode usar este canal!"
  formats:
    # Placeholders: <username>, <displayname>, <channel>, <server>, <message>, <primaryrole>, <color>
    # Also supports PlaceholderAPI
    default: '%javascript_tag%%simpleclans_tag_label%&f<displayname>&7» <color><message>'
  # CarbonChat will look for a matching group in the list below when choosing which group to use for formatting.
  # If there are no matches, the plugin will fall back to the primary-group-only option.
  # It's advised to set this option to [] if you don't want to use this.
  format-groups: []
  # If set to true, players with the permission carbonchat.group.groupname will count as having
  # The group with the name groupname (carbonchat.group.owner will count has having the group owner)
  permission-group-matching: false
  # If true, plugin will only use the format corresponding to the user's primary group (vault).
  # If false, plugin will look through the user's groups and go with the first group with a corresponding format.
  primary-group-only: true
  # The name of the vault group which should be considered as the default group.
  default-group: 'default'
  # Contexts are optional settings that modify the way channels behave.
  # For information on each contexts option, see the docs here :
  # https://github.com/Draycia/Carbon/wiki/Contexts
  contexts:
    # Used to set the range players have to be within to chat to each other
    # -1 to disable, 0 to set to world only, 1+ to set the distance.
    # EG. distance: 250 would require the players to be within 250 blocks to see each other's messages
    distance: 0
    # mcmmo-party only works when the CarbonChatMCMMO addon is installed.
    # Requires both players to be in the same party to see the message.
    mcmmo-party: false
    # worldguard-region only works when the CarbonChatWorldGuard addon is installed.
    # Requires both players to be in the same region to see the message.
    worldguard-region: false
    # towny-town only works when the CarbonChatTowny addon is installed.
    # Requires both players to be in the same town to see the message.
    towny-town: false
    # filter only works when CarbonChatModeration is installed.
    # Modifies / prevents messages depending on how filters are setup.
    filter: true
    # requires a minimum balance to chat. 0 to disable. Requires a vault-compatible economy plugin
    vault-balance: 0
    # charges on every chat message. 0 to disable. Requires a vault-compatible economy plugin
    vault-cost: 0
  # The <color> placeholder in channel formats (and other formats).
  # This option does support PlaceholderAPI placeholders, however the resulting string must be a valid color!
  color: '#FFFFFF'
  # Can players /toggle this channel and hide its messages?
  ignorable: true
  # Enables/disables cross server chat for this channel
  should-bungee: false
  # For plugin compatibility. If true, all chat messages sent will be "canceled".
  # The messages will still go through, however other plugins should assume they didn't.
  # As such, setting this on private channels is recommended.
  # For example, use this if DiscordSRV is sending messages when you don't want it to.
  cancel-message-event: false
  # For plugin compatibility. If true, this channel will use bukkit's list of players to send the messages to.
  # It's advised to leave this off unless absolutely necessary.
  honors-recipient-list: false

channels:
#
# Canal local
  local:
    name: 'Local'
    aliases: 'local|l'
    default: true
    formats:
      default: '&e[l] %javascript_tag%%simpleclans_tag_label%&f<displayname>&7» <color><message>'
    contexts:
      distance: 200
    color: '#FFFF55'
    ignorable: false
#
# Canal global
  global:
    name: 'Global'
    aliases: 'global|g'
    formats:
      default: '&2[g] %javascript_tag%%simpleclans_tag_label%&f<displayname>&7» <color><message>'
    message-prefix: '!'

contexts:
  Towny:
    cancellation-message: '<red>Você não possui uma cidade!'
  mcMMO:
    cancellation-message: '<red>Você não tem uma equipe!'

# Used for <server> placeholder in channel formats
server-name: 'Apocalipse'

item-link-placeholders:
  - '[item]'
  - '%item%'
  - '@item'
  - '@hand'

spy-prefix: '<color>[SPY] '

nicknames-set-tab-name: true

pings:
  enabled: true
  source: 'PLAYER'
  sound: 'minecraft:entity.experience_orb.pickup'
  prefix: '@'
  volume: 10.0
  pitch: 1.0
  highlight: true # independent of the "enabled" option!

whisper:
  pings:
    enabled: true
    source: 'PLAYER'
    sound: 'minecraft:entity.experience_orb.pickup'
    volume: 10.0
    pitch: 1.0

storage:
  type: JSON # JSON, MySQL
  username: 'username'
  password: 'password'
  database: 'database'
  hostname: 'localhost'
  port: 3306

# Options:
# 'bungee' - Uses bungee plugin messaging, requires BungeeCord or another proxy which supports it (Velocity!)
# 'redis' - Uses redis for cross server syncing, does not require a server proxy
# 'none' - Do not sync anything cross server, this is the default
message-system: 'none'

redis:
  host: 'localhost'
  port: 6379
  #password: 'password'
  database: 0
```

</details>

**Comment by SrBedrock** [comment]
It was a compatibility issue with another plugin that also interferes with chat.
